from items import * # imports all values from the items file
from map import rooms #imports rooms from map file

inventory = [item_id, item_laptop, item_money] # these three items are in the starting inventory
mass = items['laptop']['mass'] + items['id']['mass'] + items['money']['mass']
#the starting mass is generated by adding all the masses of the individual masses of the starting items, from the items.py dictionary
max_weight = 5 # the max weight , which will be used in the game.py to limit how much the player can carry

# Start game at the reception, as per pre set code.
current_room = rooms["Reception"]
